# ------------------------------------------------------------------------------------------------------------------------
# Reusable Workflow: Deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
name: z_template_deploy_infra
run-name: Deploy Bicep
on:
  workflow_call:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: string
      ENV_CODE:
        required: true
        type: string
      PROJECT_ROOT:
        required: false
        type: string
      APP_NAME_ENV:
        required: false
        type: string
      APP_NAME_REPO:
        required: false
        type: string
      JOB_LEVEL_VAR:
        required: false
        type: string
      RESOURCEGROUP_PREFIX:
        required: false
        type: string
      RESOURCEGROUP_LOCATION:
        required: false
        type: string
        default: ''

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Template Example
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}

    # ------------------------------------------------------------------------------------------------------------------------
    # Variables
    # ------------------------------------------------------------------------------------------------------------------------
    env:
      ENV_CODE: ${{ inputs.ENV_CODE }}
      generatedResourceGroupName: ${{ inputs.RESOURCEGROUP_PREFIX }}-${{ inputs.ENV_CODE }}
      testInput: ${{ inputs.testInput }}

    # ------------------------------------------------------------------------------------------------------------------------
    # Actions
    # ------------------------------------------------------------------------------------------------------------------------
    steps:
      - name: Template Display Variables and Files
        run: |-
          echo "inputs.ENVIRONMENT_NAME=${{ inputs.ENVIRONMENT_NAME }}"
          echo "inputs.ENV_CODE=${{ inputs.ENV_CODE }}"

          echo "PROJECT_ROOT: ${{ inputs.PROJECT_ROOT }}"
          echo "ENV_CODE: ${{ inputs.ENV_CODE }}"
          echo "APP_NAME_ENV: ${{ inputs.APP_NAME_ENV }}"
          echo "APP_NAME_REPO: ${{ inputs.APP_NAME_REPO }}"
          echo "JOB_LEVEL_VAR: ${{ inputs.JOB_LEVEL_VAR }}"

          echo "RESOURCEGROUP_PREFIX: ${{ inputs.RESOURCEGROUP_PREFIX }}"
          echo "RESOURCEGROUP_LOCATION: ${{ inputs.RESOURCEGROUP_LOCATION }}"
          echo "env.generatedResourceGroupName=${{ env.generatedResourceGroupName }}"
    
          echo "---------------------------------"
          echo "##[group]All Variables:"
          echo "Environment:"
          echo '${{ toJSON(env) }}'
          echo "Variables:"
          echo '${{ toJSON(vars) }}'
          echo "Secrets:"
          echo '${{ toJSON(secrets) }}'
          echo "Inputs:"
          echo '${{ toJSON(inputs) }}'
          echo "##[endgroup]"
          echo "---------------------------------"
          echo "##[group]Directory of ${{ github.workspace  }}"
          tree -R ${{ github.workspace  }}
          echo "##[endgroup]"
        continue-on-error: true
